/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */


buildscript {
    val ktVersion = "1.3.41"
    repositories {
        jcenter()
    }

    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$ktVersion")
    }
}

subprojects {
    repositories {
        jcenter()
    }

    apply {
        plugin("maven")
    }

    group = "ktor-swagger"
    version = "0.0.3"
}